"""
World capital cities database for World Clock module
"""

WORLD_CAPITALS = {
    # Europe
    "Madrid": {"timezone": 1, "country": "Spain"},
    "London": {"timezone": 0, "country": "United Kingdom"},
    "Paris": {"timezone": 1, "country": "France"},
    "Berlin": {"timezone": 1, "country": "Germany"},
    "Rome": {"timezone": 1, "country": "Italy"},
    "Amsterdam": {"timezone": 1, "country": "Netherlands"},
    "Brussels": {"timezone": 1, "country": "Belgium"},
    "Vienna": {"timezone": 1, "country": "Austria"},
    "Bern": {"timezone": 1, "country": "Switzerland"},
    "Stockholm": {"timezone": 1, "country": "Sweden"},
    "Oslo": {"timezone": 1, "country": "Norway"},
    "Copenhagen": {"timezone": 1, "country": "Denmark"},
    "Helsinki": {"timezone": 2, "country": "Finland"},
    "Warsaw": {"timezone": 1, "country": "Poland"},
    "Prague": {"timezone": 1, "country": "Czech Republic"},
    "Budapest": {"timezone": 1, "country": "Hungary"},
    "Athens": {"timezone": 2, "country": "Greece"},
    "Lisbon": {"timezone": 0, "country": "Portugal"},
    "Dublin": {"timezone": 0, "country": "Ireland"},
    "Moscow": {"timezone": 3, "country": "Russia"},
    
    # North America
    "Washington": {"timezone": -5, "country": "United States"},
    "Ottawa": {"timezone": -5, "country": "Canada"},
    "Mexico City": {"timezone": -6, "country": "Mexico"},
    
    # South America
    "Buenos Aires": {"timezone": -3, "country": "Argentina"},
    "Brasilia": {"timezone": -3, "country": "Brazil"},
    "Lima": {"timezone": -5, "country": "Peru"},
    "Bogota": {"timezone": -5, "country": "Colombia"},
    "Santiago": {"timezone": -4, "country": "Chile"},
    "Caracas": {"timezone": -4, "country": "Venezuela"},
    "Quito": {"timezone": -5, "country": "Ecuador"},
    "La Paz": {"timezone": -4, "country": "Bolivia"},
    "Asuncion": {"timezone": -3, "country": "Paraguay"},
    "Montevideo": {"timezone": -3, "country": "Uruguay"},
    
    # Asia
    "Tokyo": {"timezone": 9, "country": "Japan"},
    "Beijing": {"timezone": 8, "country": "China"},
    "New Delhi": {"timezone": 5.5, "country": "India"},
    "Seoul": {"timezone": 9, "country": "South Korea"},
    "Bangkok": {"timezone": 7, "country": "Thailand"},
    "Manila": {"timezone": 8, "country": "Philippines"},
    "Jakarta": {"timezone": 7, "country": "Indonesia"},
    "Singapore": {"timezone": 8, "country": "Singapore"},
    "Kuala Lumpur": {"timezone": 8, "country": "Malaysia"},
    "Hanoi": {"timezone": 7, "country": "Vietnam"},
    "Dhaka": {"timezone": 6, "country": "Bangladesh"},
    "Colombo": {"timezone": 5.5, "country": "Sri Lanka"},
    "Kathmandu": {"timezone": 5.75, "country": "Nepal"},
    "Islamabad": {"timezone": 5, "country": "Pakistan"},
    "Kabul": {"timezone": 4.5, "country": "Afghanistan"},
    "Tashkent": {"timezone": 5, "country": "Uzbekistan"},
    "Astana": {"timezone": 6, "country": "Kazakhstan"},
    "Bishkek": {"timezone": 6, "country": "Kyrgyzstan"},
    "Dushanbe": {"timezone": 5, "country": "Tajikistan"},
    "Ashgabat": {"timezone": 5, "country": "Turkmenistan"},
    "Ulaanbaatar": {"timezone": 8, "country": "Mongolia"},
    "Pyongyang": {"timezone": 9, "country": "North Korea"},
    
    # Middle East
    "Riyadh": {"timezone": 3, "country": "Saudi Arabia"},
    "Tehran": {"timezone": 3.5, "country": "Iran"},
    "Baghdad": {"timezone": 3, "country": "Iraq"},
    "Kuwait City": {"timezone": 3, "country": "Kuwait"},
    "Doha": {"timezone": 3, "country": "Qatar"},
    "Manama": {"timezone": 3, "country": "Bahrain"},
    "Muscat": {"timezone": 4, "country": "Oman"},
    "Abu Dhabi": {"timezone": 4, "country": "United Arab Emirates"},
    "Amman": {"timezone": 2, "country": "Jordan"},
    "Beirut": {"timezone": 2, "country": "Lebanon"},
    "Damascus": {"timezone": 2, "country": "Syria"},
    "Jerusalem": {"timezone": 2, "country": "Israel"},
    "Ankara": {"timezone": 3, "country": "Turkey"},
    "Nicosia": {"timezone": 2, "country": "Cyprus"},
    "Tbilisi": {"timezone": 4, "country": "Georgia"},
    "Yerevan": {"timezone": 4, "country": "Armenia"},
    "Baku": {"timezone": 4, "country": "Azerbaijan"},
    
    # Africa
    "Cairo": {"timezone": 2, "country": "Egypt"},
    "Tunis": {"timezone": 1, "country": "Tunisia"},
    "Algiers": {"timezone": 1, "country": "Algeria"},
    "Rabat": {"timezone": 1, "country": "Morocco"},
    "Tripoli": {"timezone": 2, "country": "Libya"},
    "Khartoum": {"timezone": 2, "country": "Sudan"},
    "Addis Ababa": {"timezone": 3, "country": "Ethiopia"},
    "Nairobi": {"timezone": 3, "country": "Kenya"},
    "Kampala": {"timezone": 3, "country": "Uganda"},
    "Kigali": {"timezone": 2, "country": "Rwanda"},
    "Dar es Salaam": {"timezone": 3, "country": "Tanzania"},
    "Lusaka": {"timezone": 2, "country": "Zambia"},
    "Harare": {"timezone": 2, "country": "Zimbabwe"},
    "Pretoria": {"timezone": 2, "country": "South Africa"},
    "Gaborone": {"timezone": 2, "country": "Botswana"},
    "Windhoek": {"timezone": 2, "country": "Namibia"},
    "Maputo": {"timezone": 2, "country": "Mozambique"},
    "Antananarivo": {"timezone": 3, "country": "Madagascar"},
    "Abuja": {"timezone": 1, "country": "Nigeria"},
    "Accra": {"timezone": 0, "country": "Ghana"},
    "Dakar": {"timezone": 0, "country": "Senegal"},
    "Bamako": {"timezone": 0, "country": "Mali"},
    "Ouagadougou": {"timezone": 0, "country": "Burkina Faso"},
    "Conakry": {"timezone": 0, "country": "Guinea"},
    "Freetown": {"timezone": 0, "country": "Sierra Leone"},
    "Monrovia": {"timezone": 0, "country": "Liberia"},
    "Yamoussoukro": {"timezone": 0, "country": "Ivory Coast"},
    "Porto-Novo": {"timezone": 1, "country": "Benin"},
    "Lome": {"timezone": 0, "country": "Togo"},
    "Libreville": {"timezone": 1, "country": "Gabon"},
    "Yaounde": {"timezone": 1, "country": "Cameroon"},
    "Bangui": {"timezone": 1, "country": "Central African Republic"},
    "N'Djamena": {"timezone": 1, "country": "Chad"},
    "Kinshasa": {"timezone": 1, "country": "Democratic Republic of Congo"},
    "Brazzaville": {"timezone": 1, "country": "Republic of Congo"},
    "Luanda": {"timezone": 1, "country": "Angola"},
    
    # Oceania
    "Canberra": {"timezone": 10, "country": "Australia"},
    "Wellington": {"timezone": 12, "country": "New Zealand"},
    "Suva": {"timezone": 12, "country": "Fiji"},
    "Port Moresby": {"timezone": 10, "country": "Papua New Guinea"},
    "Honiara": {"timezone": 11, "country": "Solomon Islands"},
    "Port Vila": {"timezone": 11, "country": "Vanuatu"},
    "Nuku'alofa": {"timezone": 13, "country": "Tonga"},
    "Apia": {"timezone": 13, "country": "Samoa"},
    "Majuro": {"timezone": 12, "country": "Marshall Islands"},
    "Palikir": {"timezone": 11, "country": "Micronesia"},
    "Ngerulmud": {"timezone": 9, "country": "Palau"},
    "Funafuti": {"timezone": 12, "country": "Tuvalu"},
    "Tarawa": {"timezone": 12, "country": "Kiribati"},
    "Yaren": {"timezone": 12, "country": "Nauru"}
}
